binder_sources := \
	AppOpsManager.cpp \
	Binder.cpp \
	BpBinder.cpp \
	BufferedTextOutput.cpp \
	Debug.cpp \
	IAppOpsCallback.cpp \
	IAppOpsService.cpp \
	IBatteryStats.cpp \
	IInterface.cpp \
	IMemory.cpp \
	IPCThreadState.cpp \
	IPermissionController.cpp \
	IServiceManager.cpp \
	MemoryBase.cpp \
	MemoryDealer.cpp \
	MemoryHeapBase.cpp \
	Parcel.cpp \
	PermissionCache.cpp \
	ProcessInfoService.cpp \
	ProcessState.cpp \
	Static.cpp \
	TextOutput.cpp

objects += $(patsubst %.cpp,binder/%.o, $(binder_sources))