cutils_sources := \
	ashmem-dev.c \
	ashmem-host.c \
	atomic.c \
	native_handle.c \
	process_name.c \
	properties.c \
	safe_iop.c \
	sched_policy.c \
	socket_inaddr_any_server.c \
	socket_local_client.c \
	socket_local_server.c \
	socket_loopback_client.c \
	socket_loopback_server.c \
	sockets.c \
	threads.c

objects += $(patsubst %.c,cutils/%.o, $(cutils_sources))